### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/user-cards#1]
https://github.com/DenisPitsul/user-cards/blob/ce6b48e892cd4c8b0a270255c9a467351e29559a/index.html#L28
- це не окрема структурна одиниця, а контейнер для основного контенту секції з h2, тому краще div

https://github.com/DenisPitsul/user-cards/blob/ce6b48e892cd4c8b0a270255c9a467351e29559a/index.html#L710
- по значущості не тягне на заголовок, навіть з точки зору SEO

**Comment by DenisPitsul** [comment]
Fixed in commits:
https://github.com/DenisPitsul/user-cards/commit/3955f0014c6ba230b5ef0c43e87baae47b51e857
https://github.com/DenisPitsul/user-cards/commit/20ab4eab5519f222c88ed363b09a9faa12ffffc7
