### ISSUE TITLE
шрифти

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/user-cards#2]
https://github.com/DenisPitsul/user-cards/blob/ce6b48e892cd4c8b0a270255c9a467351e29559a/assets/css/styles.css#L7
- буде плюсом додати резервні шрифти: 

> Першим ви вказуєте шрифт, який хотіли б використовувати. За ним йдуть будь-які шрифти, які ви могли б використовувати, якщо перший зазначений шрифт недоступний. А закінчити список ви повинні типовим шрифтом, який має 5 видів: serif, sans-serif, monospace, cursive та fantasy

(https://www.w3.org/Style/Examples/007/fonts.uk.html)

**Comment by DenisPitsul** [comment]
Fixed in commit: 
https://github.com/DenisPitsul/user-cards/commit/dcf7989b2e9a04f6640ff3ef7924b39211d93a49
