### ISSUE TITLE
ширина

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/user-cards#3]
https://github.com/DenisPitsul/user-cards/blob/ce6b48e892cd4c8b0a270255c9a467351e29559a/assets/css/styles.css#L135
- при фіксованій ширині є ймовірність преповнення:
![image](https://github.com/DenisPitsul/user-cards/assets/67504221/a69feb27-1ae7-4d24-96da-c3d9b690e7b1)
відповідно, надійніше вказати максимальну ширину та вказати, щоб займало весь доступний простір:
```css
    max-width: 200px;
    width: 100%;
```

**Comment by DenisPitsul** [comment]
Fixed in commit: 
https://github.com/DenisPitsul/user-cards/commit/5add5ae6dcaca39c3071a784761bc08f374623a5
