### ISSUE TITLE
друкарська помилка

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/user-cards#4]
https://github.com/DenisPitsul/user-cards/blob/ce6b48e892cd4c8b0a270255c9a467351e29559a/assets/css/styles.css#L180
- просто пощастило, що очікувана поведінка співпала з бажаною) Це, доречі, найгірший вид помилок, коли ти думаєш, що це воно так працює тому, що ти так написав, а по факту просто зірки зійшлися, і на інших даних ця помилка може показати себе у всій красі)

**Comment by DenisPitsul** [comment]
Fixed in commit: 
https://github.com/DenisPitsul/user-cards/commit/a754bfe741fc10ce67509d4c29d678ec1732b703
