### ISSUE TITLE
висота картинки

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/user-cards#5]
https://github.com/DenisPitsul/user-cards/blob/ce6b48e892cd4c8b0a270255c9a467351e29559a/assets/css/styles.css#L319
 - тут незручно, що висота на зображення чітко фіксується, але реально картинка займе стільки, щоб бути пропорційною, і якщо картка стає вужчою, картинка звужується і її висота зменшується, але реально виділена в контейнері під неї висота буде вже завелика і буде вільний незаповнений простір під карткою. Тому тут надійніше вказати максимальну допустиму висоту, на випадок високої картинки.

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/user-cards/commit/a00e63a30c68bd9999d5a1ec41f6885aba945451
