### ISSUE TITLE
приховання елементів

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/user-cards#6]
https://github.com/DenisPitsul/user-cards/blob/87d5ab09a3ccd63af9aaa5dfbf695bdef58f2d52/assets/css/styles.css#L521
- приховувати елементи треба з обережністю обираючи слушний спосіб. В даному випадку це, скоріш за все, якийсь інформативний текст, тому він має бути доступний засобам читання з екрану, навіть якщо ми його візуально приховаємо. Тому краще обрати щось інше, наприклад, зменшити шрифт/відступи до 0 (https://ishadeed.com/article/hiding-web/, https://codepen.io/shadeed/embed/rNadMdo/7966b332f98df32f2cf2fde2e5dbd28d).

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/user-cards/commit/58e8c5b89dade93f4f649913ea63d62df465d560
